import { Raleway } from 'next/font/google';
import { Quicksand } from 'next/font/google';

import ScrollButton from "@/components/scrollButton";

import "./globals.css";

const raleway = Raleway({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
});

const quicksand = Quicksand({
  weight: ['300', '400', '500', '600', '700'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: "Pasticceria a Varese | C'est La Vie",
  description: "Generated by Agostini, Chen & Falese",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${raleway.className} ${quicksand.className}`}>
        <main>
          {children}
          <ScrollButton />
        </main>
      </body>
    </html>
  );
}
